apiVersion: v1
kind: Pod
metadata:
  name: release-nginx
  labels:
    app: release-nginx 
spec:
   containers:
      - name: release-nginx
        image: srinath2586/cloudethix_release_nginx_srinathk:nginx-release
        ports:
        - containerPort: 80
