apiVersion: v1
kind: Pod
metadata:
  name: node-release-nginx
  labels:
    app: node-release-nginx
spec:
   nodeName: k8s-worker2
   containers:
      - name: node-release-nginx
        image: srinath2586/cloudethix_release_nginx_srinathk:nginx-release
        ports:
        - containerPort: 80

