apiVersion: v1
kind: Pod
metadata:
  name: node-master-nginx
  labels:
    app: node-master-nginx
spec:
   nodeName: k8s-worker1
   containers:
      - name: node-master-nginx
        image: srinath2586/cloudethix_master_nginx_srinathk:nginx-master
        ports:
        - containerPort: 80
