---
apiVersion: v1
kind: Service
metadata:
  name: frontend-webapp-configmap-service
spec:
  selector:
    app: frontend-webapp-configmap
#    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort : 30008
  type: NodePort
...

