apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp 
  labels:
    app: flask-webapp 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-webapp 
  strategy:
     rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
     type: RollingUpdate/Recreate
  template:
    metadata:
      labels:
        app: flask-webapp 
    spec:
      containers:
      - name: flask-webapp 
        image: srinath2586/flask_webapp_srinathk:simple-webapp-docker-v1
        ports:
        - containerPort: 8080
